[package]
name = "snake"
version = "0.1.0"
edition = "2021"
authors = ["Zwazel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6.1", features = ["dynamic"] }
rand = { version = "0.8.5"}